// Generated by gencpp from file my_msgs_p/user_control_msgs.msg
// DO NOT EDIT!


#ifndef MY_MSGS_P_MESSAGE_USER_CONTROL_MSGS_H
#define MY_MSGS_P_MESSAGE_USER_CONTROL_MSGS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_msgs_p
{
template <class ContainerAllocator>
struct user_control_msgs_
{
  typedef user_control_msgs_<ContainerAllocator> Type;

  user_control_msgs_()
    : need_stop(0)  {
    }
  user_control_msgs_(const ContainerAllocator& _alloc)
    : need_stop(0)  {
  (void)_alloc;
    }



   typedef int64_t _need_stop_type;
  _need_stop_type need_stop;





  typedef boost::shared_ptr< ::my_msgs_p::user_control_msgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs_p::user_control_msgs_<ContainerAllocator> const> ConstPtr;

}; // struct user_control_msgs_

typedef ::my_msgs_p::user_control_msgs_<std::allocator<void> > user_control_msgs;

typedef boost::shared_ptr< ::my_msgs_p::user_control_msgs > user_control_msgsPtr;
typedef boost::shared_ptr< ::my_msgs_p::user_control_msgs const> user_control_msgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs_p::user_control_msgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs_p::user_control_msgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_msgs_p::user_control_msgs_<ContainerAllocator1> & lhs, const ::my_msgs_p::user_control_msgs_<ContainerAllocator2> & rhs)
{
  return lhs.need_stop == rhs.need_stop;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_msgs_p::user_control_msgs_<ContainerAllocator1> & lhs, const ::my_msgs_p::user_control_msgs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_msgs_p

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_msgs_p::user_control_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs_p::user_control_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs_p::user_control_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs_p::user_control_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs_p::user_control_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs_p::user_control_msgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs_p::user_control_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8171a97e85519dd4fe2e897b160f54e4";
  }

  static const char* value(const ::my_msgs_p::user_control_msgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8171a97e85519dd4ULL;
  static const uint64_t static_value2 = 0xfe2e897b160f54e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs_p::user_control_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs_p/user_control_msgs";
  }

  static const char* value(const ::my_msgs_p::user_control_msgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs_p::user_control_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 need_stop\n"
;
  }

  static const char* value(const ::my_msgs_p::user_control_msgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs_p::user_control_msgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.need_stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct user_control_msgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs_p::user_control_msgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs_p::user_control_msgs_<ContainerAllocator>& v)
  {
    s << indent << "need_stop: ";
    Printer<int64_t>::stream(s, indent + "  ", v.need_stop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_P_MESSAGE_USER_CONTROL_MSGS_H
